### PR TITLE
I made some cool changes! Click here if u don't want to get rickrolled!

### PR DESCRIPTION
**Pull request by joeyk710**
hope u like them :D #15 
https://github.com/SudhanPlayz/Discord-MusicBot

image
image

https://www.youtube.com/watch?v=p4lP96Tiv9s
THIS HAS MORE VIEWS THAN YOURS HAHAHAHA

Btw ur description says "high professional". do you even know how to speak english? 

https://discord.com/invite/a9SHDpD

No matter how many times you may remove comments that I make, I will continue to spam every single time until you remove your project and realize how bad plagiarism is and how illegal it is. Do you think you coded this bot? 

I would like to see you type code and make it yourself instead of being a bitch and copying someone else's work.

### CODE REVIEW

**Comment by ItzSudhan** [comment]
👀

**Comment by joeyk710** [comment]
imagine coding ur own bot? hm its so funny that i was banned from this discord server after some people are being babies about copying. if you did this at a real job, you would be fired.

**Comment by joeyk710** [comment]
So why did u close it? Are u too scared that u won't get caught?

**Comment by joeyk710** [comment]
aw im sorry u dont like my changes

its ok, we have over 300 forks and over 900 members in our server so u are nothing compared to us. go to hell and you will pay for copying our code

Our code was posted last year while you posted this days ago. how did we steal your code if our code was posted before yours? 

i would like to talk to you about this. if you are feeling up to talking about this, join our discord if you weren't already banned from it you piece of shit

**Comment by testbot123-cmd** [comment]
Yeah, do not copy and republish others code!!

**Pull request closed without merging**
