### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mrmotchy**

### CODE REVIEW

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by joeyk710** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by jnspleet** [comment]
STOLEN CODE

@mrmotchy you have stolen the code for this bot from our bot here - https://github.com/SudhanPlayz/Discord-MusicBot

you cannot do this and make this public as this violates out license

**Comment by ghost** [comment]
repeating yourself over and over again will not help. you can report him or the repo i believe

**Pull request merged**
